### ISSUE TITLE
Minimum resolution required/suggested

### ISSUE THREAD

**Issue by Konesuke** [pihnat/rpi-Candle#3]
Does this work well on the rft screen 3,5" 320x480?

**Comment by pihnat** [comment]
I haven't tried it with any smaller screens but about 4 years ago when Candle was first tried on a raspi I did try it with the raspi 7" screen (see  https://github.com/Denvi/Candle/issues/77  ). It sort of worked but when you opened say the settings page the "ok" and "cancel" buttons were off the screen so you couldn't close the pop-up box. This might also be the case with the current rpi build of Candle, I don't know, I haven't tried it.
However one thing for sure - with a 3.5"screen all the buttons will be very small and tricky to operate. 320x480 is quite low resolution too so I don't know how the control panel would look.
Safety is an important issue with any CNC machine so having a larger display and therefore having larger buttons would definitely be recommended. Otherwise you could modify the program so that the important buttons are available on the 3.5" screen without some of the other graphics.
